<?php
/**
 * PaymentCreateTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Prepaid-Host API
 *
 * Auf dieser Seite findest du die API Dokumentation von Prepaid-Host.com
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.40
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PaymentCreateTest Class Doc Comment
 *
 * @category    Class
 * @description PaymentCreate
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PaymentCreateTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PaymentCreate"
     */
    public function testPaymentCreate()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "payment_method_"
     */
    public function testPropertyPaymentMethod_()
    {
    }

    /**
     * Test attribute "ok_url"
     */
    public function testPropertyOkUrl()
    {
    }

    /**
     * Test attribute "nok_url"
     */
    public function testPropertyNokUrl()
    {
    }

    /**
     * Test attribute "pn_url"
     */
    public function testPropertyPnUrl()
    {
    }

    /**
     * Test attribute "reason"
     */
    public function testPropertyReason()
    {
    }
}
