<?php
/**
 * DomainApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Prepaid-Host API
 *
 * Auf dieser Seite findest du die API Dokumentation von Prepaid-Host.com
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.40
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * DomainApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DomainApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for domainIdAddPost
     *
     * Fügt ein DNS Eintag zu der Domain hinzu.
     *
     */
    public function testDomainIdAddPost()
    {
    }

    /**
     * Test case for domainIdDNSGet
     *
     * Gibt eine Liste der aktuellen DNS Einträge der Domain zurück.
     *
     */
    public function testDomainIdDNSGet()
    {
    }

    /**
     * Test case for domainIdDeleteDelete
     *
     * Löscht ein DNS Eintag zu der Domain hinzu.
     *
     */
    public function testDomainIdDeleteDelete()
    {
    }

    /**
     * Test case for domainIdGet
     *
     * Gibt Infos zu einer Domain aus.
     *
     */
    public function testDomainIdGet()
    {
    }

    /**
     * Test case for domainListGet
     *
     * Gibt eine Liste der aktuellen Domains zurück.
     *
     */
    public function testDomainListGet()
    {
    }
}
