<?php
/**
 * RootserverApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Prepaid-Host API
 *
 * Auf dieser Seite findest du die API Dokumentation von Prepaid-Host.com
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.40
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * RootserverApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RootserverApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for rootserverIdAddressesGet
     *
     * Gibt die IP Adressen des Rootservers aus.
     *
     */
    public function testRootserverIdAddressesGet()
    {
    }

    /**
     * Test case for rootserverIdRestartPost
     *
     * Startet den gewünschten Rootserver neu.
     *
     */
    public function testRootserverIdRestartPost()
    {
    }

    /**
     * Test case for rootserverIdStartPost
     *
     * Startet den gewünschten Rootserver.
     *
     */
    public function testRootserverIdStartPost()
    {
    }

    /**
     * Test case for rootserverIdStatsGet
     *
     * Gibt den aktuellen Status der Rootserver durch.
     *
     */
    public function testRootserverIdStatsGet()
    {
    }

    /**
     * Test case for rootserverIdStopPost
     *
     * Stoppt den gewünschten Rootserver.
     *
     */
    public function testRootserverIdStopPost()
    {
    }

    /**
     * Test case for rootserverListGet
     *
     * Gibt eine Liste der aktuellen Rootserver zurück.
     *
     */
    public function testRootserverListGet()
    {
    }
}
